"""Sphinx configuration for Credit Card Stripe Parser documentation."""

import os
import sys
from datetime import datetime

# Add the project root to the Python path
sys.path.insert(0, os.path.abspath('../../..'))

# Import package metadata
from credit_card_stripe_parser.about import (
    APP_NAME, VERSION, AUTHOR, YEAR, GITHUB_URL, DESCRIPTION
)

# -- Project information -----------------------------------------------------

project = APP_NAME
author = AUTHOR
copyright = f"{YEAR}, {AUTHOR}"  # noqa: A001
version = VERSION
release = VERSION

# The master toctree document
master_doc = 'index'

# Short description
project_short_description = "A tool for parsing and analyzing credit card magnetic stripe data"

# GitHub repository
github_repo = "Nsfr750/credit_card_stripe_parser"
github_url = f"https://github.com/{github_repo}"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.intersphinx',
    'sphinx.ext.autosectionlabel',
    'sphinx_rtd_theme',
    'autoapi.extension',
    'myst_parser',
]

# AutoAPI configuration
autoapi_type = 'python'
autoapi_dirs = ['../../credit_card_stripe_parser']
autoapi_ignore = ['*tests*', '*__pycache__*']
autoapi_options = [
    'members',
    'undoc-members',
    'show-inheritance',
    'show-module-summary',
    'special-members',
    'imported-members',
]

# Intersphinx configuration
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'sphinx': ('https://www.sphinx-doc.org/en/master/', None),
}

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_type_aliases = None

# MyST Parser configuration
myst_enable_extensions = [
    'colon_fence',
    'deflist',
    'dollarmath',
    'html_admonition',
    'html_image',
    'linkify',
    'replacements',
    'smartquotes',
    'substitution',
]

# Add any paths that contain templates here, relative to this directory
templates_path = ['_templates']

# The suffix(es) of source filenames
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document
master_doc = 'index'

# The language for content autogenerated by Sphinx
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing
todo_include_todos = True

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages
html_theme = 'sphinx_rtd_theme'

# Theme options
html_theme_options = {
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_position': 'both',
    'style_external_links': True,
    'style_nav_header_background': '#2980B9',
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False,
}

# Add any paths that contain custom static files (such as style sheets) here
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'relations.html',
        'searchbox.html',
        'donate.html',
    ]
}

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder
htmlhelp_basename = 'CreditCardStripeParserDoc'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '10pt',
    'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files
latex_documents = [
    (
        master_doc,
        'CreditCardStripeParser.tex',
        'Credit Card Stripe Parser Documentation',
        AUTHOR,
        'manual',
    ),
]

# -- Options for manual page output ------------------------------------------

man_pages = [
    (
        master_doc,
        'credit-card-stripe-parser',
        'Credit Card Stripe Parser Documentation',
        [AUTHOR],
        1,
    )
]

# -- Options for Texinfo output ----------------------------------------------
texinfo_documents = [
    (
        master_doc,
        'CreditCardStripeParser',
        'Credit Card Stripe Parser Documentation',
        AUTHOR,
        'CreditCardStripeParser',
        'A tool for parsing credit card magnetic stripe data',
        'Miscellaneous',
    ),
]

# -- Extension configuration -------------------------------------------------

# Enable todo output
todo_include_todos = True

# -- Options for autodoc ----------------------------------------------------
# Mock imports that might not be available when building docs
autodoc_mock_imports = []

# Sort members by source order
autodoc_member_order = 'bysource'

def setup(app):
    app.add_css_file('custom.css')
    app.add_js_file('custom.js')

# -- Options for linkcheck ---------------------------------------------------
linkcheck_ignore = [
    r'http://localhost:\d+/?',
    r'https://github\.com/.*#.*',  # GitHub anchors are checked by the CI
]

linkcheck_retries = 3
linkcheck_timeout = 5
linkcheck_workers = 5

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings
# extensions = [
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# -- Extension configuration -------------------------------------------------

# Autodoc settings
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = True
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_type_aliases = None

# Todo settings
todo_include_todos = True
